### ISSUE TITLE
Timing for Brian simulator

### ISSUE THREAD

**Issue by thesamovar** [nasiryahm/SNNSimulatorComparison#1]
Hi, just a quick note from the Brian simulator guys after reading your preprint. It looks like you're benchmarking simulation time not including build time in this code:

```
starttime = timeit.default_timer()
run(simtime)
totaltime = timeit.default_timer() - starttime
```

However, this will include some one-off build time steps. A better way to benchmark is like this:

```
run(0*second)
starttime = timeit.default_timer()
run(simtime)
totaltime = timeit.default_timer() - starttime
```

This still includes some build steps, and so another method (which gives a slight underestimate as it doesn't include some very small amount of time spent in Python is):

```
run(0*ms)
starttime = timeit.default_timer()
run(simtime, profile=True)
totaltime_overestimate = timeit.default_timer() - starttime
totaltime_underestimate = sum(profiling_summary().times)
```

You can also use the standalone mode of Brian, which is often much faster than the runtime mode. To use the standalone mode, include this at the top of your script:

```
set_device('cpp_standalone')
```

Only the underestimate timing will work now:

```
run(simtime, profile=True)
totaltime_underestimate = sum(profiling_summary().times)
```

No worries if the paper's already accepted, but would be great to include updated timings and the standalone timings if it's still in review.

**Comment by thesamovar** [comment]
@mstimberg in case he has anything else to add.

**Comment by nasiryahm** [comment]
Thanks for the feedback -- I really appreciate it.

I tried to be fair to all simulators by ignoring build times for everyone. I will (at minimum) include the zero second pre-run to catch any one-off build steps but keep any further comments coming.

I will leave this issue open until I've had time to make that change and recreate the plots. Paper has been submitted but not yet reviewed so this is perfect timing.

Cheers

**Comment by thesamovar** [comment]
That's great! Thanks for your efforts on that. Doing a fair benchmark is incredibly hard I think.

I also just remembered that when we were doing our own benchmarking (of brian2genn I think) we actually added an undocumented feature specifically to do this properly, so this should be the most accurate timing possible (and works for both standalone and runtime mode):

```
run(simtime, profile=True)
totaltime = device._last_run_time
```

That includes all the time spent in the run loop with all the one-off overheads subtracted off, and with that you don't need to include the ``run(0*ms)``. However, do make sure that you always run the code twice and take the second value (because the first time it runs it needs to compile the code, but the second time it uses a cached copy) - I think you must already be doing this because otherwise the numbers would be much bigger!

**Comment by nasiryahm** [comment]
Perfect! I'll use that variable when I re-do the benchmarks. Cheers.

For Brian2GeNN I did find the initial compile overhead and to avoid overcomplicating things I ended up benchmarking pure GeNN (C++) code. So in the end I don't have a direct comparison to Brian2GeNN.

**Comment by nasiryahm** [comment]
On that note I have a number of publications to add as references to the preprint - including those for Brian2GeNN and more recent benchmarks of theirs. Big fan of the Brian2 frontend with GeNN backend!

**Comment by thesamovar** [comment]
Sounds reasonable. It should be more or less the same I guess (maybe pure GeNN slightly faster because of simplified hand-written expressions rather than auto-generated ones).

Thanks! I have to admit I haven't had a chance to try Spike yet myself, but I'm very interested to see if we can integrate your timestep grouping optimisation.

**Comment by thesamovar** [comment]
Do let us know if/when you get a chance to redo the benchmarks, would love to see the updated figure from your paper. Redoing the benchmarks from another paper I got the time dropping from 6s (about the same as in the paper that did it) to 4s using ``device._last_run_time``, and 1.2s using standalone mode, so it can make quite a difference.

**Comment by nasiryahm** [comment]
Hi Dan - I attempted to make some of these changes today and ran into a few issues. Any advice you have would be great. For I am testing these changes with both the [VogelsAbbott benchmark](https://github.com/nasiryahm/SNNSimulatorComparison/blob/master/Benchmarks/VogelsAbbott/brian2/COBA.py) and the [Brunel benchmark](https://github.com/nasiryahm/SNNSimulatorComparison/blob/master/Benchmarks/Brunel/brian2/Brunel10K.py).

First, I wanted to make sure that you are aware that I run all of these benchmarks for 100s of simulation time and then form a normalized simulation time for the plots. I.e. the result shown in the curves is the average time per second of simulation (averaged over 100s).

In the end, running the simulation with an initial 'burn in' of zero seconds produced almost no difference in time for the benchmarks. I'm unsure of why this is, given your experience in the change in run time. I tested this both using `device._last_run_time` and by initially `run(0*second)` before timing the run time. See the updated scripts for that change. The difference in runtime was less than 1% compared to before this change.

Attempting to use standalone mode using;
```
set_device('cpp_standalone')
```

Gives the error message that follows (the error is an example for the VogelAbbott case). I imagine that I can't get around this since all simulations load a weight matrix for a fair comparison ( and the standalone version does not support weight matrix loading I guess?).

If you have any other thoughts I'm happy to test them. 


```
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team
/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_lVABdp.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_qZPXIs.py Thanks! [brian2]
Traceback (most recent call last):
  File "COBA.py", line 99, in <module>
    conn_ee.w[:,:]=we
  File "/home/nas/anaconda2/envs/simulatorcomparison/lib/python2.7/site-packages/brian2/core/variables.py", line 927, in __setitem__
    self.set_item(item, value, level=1)
  File "/home/nas/anaconda2/envs/simulatorcomparison/lib/python2.7/site-packages/brian2/core/variables.py", line 924, in set_item
    check_units=check_units)
  File "/home/nas/anaconda2/envs/simulatorcomparison/lib/python2.7/site-packages/brian2/core/base.py", line 276, in device_override_decorated_function
    return getattr(curdev, name)(*args, **kwds)
  File "/home/nas/anaconda2/envs/simulatorcomparison/lib/python2.7/site-packages/brian2/devices/cpp_standalone/device.py", line 429, in variableview_set_with_index_array
    'expressions.') % variableview.name)
NotImplementedError: Cannot set variable "w" this way in standalone, try using string expressions.
```

**Comment by thesamovar** [comment]
For the ``conn_ee.w[:,:]=we`` line it should be ok to just change to ``conn_ee.w=we`` and this should work. You've already created the matrix in the line above and this worked, this is just setting its value to a constant.

The reason the 0s burn in time makes no difference is probably because you run for 100s of simulated time - sorry I thought you were running for just 1s for some reason. With 100s the one-off cost is probably pretty small (although still ``device._last_run_time`` is safer).

**Comment by nasiryahm** [comment]
Standalone mode makes a real difference to simulation speed - plots are updated and re-ordered according to speed. See commit; 0b2ba17

I've inserted both `set_device('cpp_standalone')` and I now use `device._last_run_time` for simulation timing of Brian2. Plots are updated and show a significant speed increase (in absolute time) for both benchmarks. The impact is significant especially for the VogelsAbbott benchmark but less significant (as a percent of time) for the Brunel benchmark.

I appreciate the input. Some interaction with other developers so that we can have a space with real speed comparisons and example models was exactly what I hoped for and opening an issue for this was a great idea. Let's keep in touch :)

**Comment by thesamovar** [comment]
That's great - thanks for that!
